host: "0.0.0.0"
port: 7047
html_info: |
  <h1>Notary Server {version}!</h1>
  <ul>
  <li>git commit hash: <a href="https://github.com/tlsnotary/tlsn/commit/{git_commit_hash}">{git_commit_hash}</a></li>
  <li>git commit timestamp: {git_commit_timestamp}</li>
  <li>public key: <pre>{public_key}</pre></li>
  </ul>
  <a href="/healthcheck">health check</a> - <a href="/info">info</a><br/>

notarization:
  max_sent_data: 14096
  max_recv_data: 16384
  timeout: 1800
  private_key_path: "/root/.notary/notary.key"
  signature_algorithm: secp256k1
  allow_extensions: false

tls:
  enabled: false

log:
  level: DEBUG
  format: COMPACT

auth:
  enabled: false

concurrency: 32
