services:
  vlayer-call-server:
    depends_on:
      - anvil-l1
      - anvil-l2-op
    image: ghcr.io/vlayer-xyz/call_server:latest
    container_name: vlayer-call-server
    pull_policy: always
    environment:
      RUST_LOG: "info,call_engine=debug"
    command: "--config-file /config.toml"
    ports:
      - "127.0.0.1:3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 5s
      timeout: 60s
      retries: 10
      start_period: 5s
    volumes:
      - ./config.toml:/config.toml
